FROM golang:1.19-alpine3.16 AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN go build -ldflags '-s -w' ./cmd/ionscale

FROM alpine:3.16
WORKDIR /app
COPY --from=build /app/ionscale /usr/local/bin/ionscale
VOLUME ["/data/conf","/data/db"]
ENTRYPOINT ["/usr/local/bin/ionscale"]
CMD ["server", "--config", "/data/conf/ionscale.yaml"]
